packages:
  - name: typeform-webhook
    functions:
      - name: __main__
        runtime: 'python:3.11'
        main: '__main__.py'
        environment:
          DB_USER: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}
          DB_HOST: ${DB_HOST}
          DB_PORT: ${DB_PORT}
          DB_NAME: ${DB_NAME}
          ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}